import './globals.css';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import { StoreProvider } from '@/redux/StoreProvider';

const sans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-open-sans',
});

export const metadata: Metadata = {
  title: 'Yesdok.com',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sans.className}>
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
