import '../styles/globals.css';
import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import { Providers } from './providers';

const opensans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-open-sans',
});

export const metadata: Metadata = {
  title: 'Yesdok.com',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body className={opensans.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
